#!/bin/bash

# This is structured as an if/elif/then statement to allow you to choose the version of OrthoFinder you want to run on Cornell's BioHPC.
if [[ $1 == '2.4.0' ]]; then
  echo Running OrthoFinder v. $1
  cd /workdir/$USER/FormicidaeMolecularEvolution

  wget https://github.com/davidemms/OrthoFinder/releases/latest/download/OrthoFinder.tar.gz

  tar xvfz OrthoFinder.tar.gz
  rm OrthoFinder.tar.gz

  # set environment
  export PATH=/programs/python2_link:$PATH
  export PATH=/programs/FastTree-2.1.10:$PATH
  export PATH=/workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/orthofinder:/workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/orthofinder/bin:/programs/muscle:/programs/RAxML-8.2.12:/programs/raxml-ng_v0.8.1:/programs/iqtree-1.6.10-Linux/bin:/programs/mafft/bin:$PATH

  mkdir /workdir/tmp
  mkdir /workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/fasta
  cp ./TranslatedData/OutputFiles/translated* ./OrthoFinder/fasta
  cd ./OrthoFinder/fasta
  rename translated '' translated*
  cd ../

  ## command, using diamond for alignment, use "-I 5" for tight cluster, run 4 jobs at a time, use /workdir/tmp as the tmp directory. "-f fasta": the directory name of input fasta files; -og stop after get ortholog groups.
  ./orthofinder -S diamond -I 5 -t 32 -a 4 -f /workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/fasta -M msa -p /workdir/tmp

  echo Finished running OrthoFinder v. $1

elif [[ $1 == '2.3.8' ]]; then
echo Running OrthoFinder v. $1
cd /workdir/$USER/FormicidaeMolecularEvolution

  # This script will run Orthofinder 2.3.8 on all of the genomes, identifying orthogroups (genes descended from a common gene in the common ancestor).

  # Make a directory in which to run OrthoFinder:
  mkdir ./OrthoFinder
  cd ./OrthoFinder
  mkdir ./fasta

  # First set up the BioHPC to run OrthoFinder:
  export PATH=/programs/python2_link:$PATH
  cp -r /programs/OrthoFinder-2.3.8_source/orthofinder $HOME/
  export PATH=$HOME/orthofinder:$HOME/orthofinder/bin:/programs/muscle:/programs/RAxML-8.2.12:/programs/raxml-ng_v0.8.1:/programs/iqtree-1.6.10-Linux/bin:/programs/mafft/bin:$PATH
  export PATH=/programs/FastTree-2.1.10:$PATH
  mkdir /workdir/tmp

  # Copy the input files to the primary_transcripts directory:
  cp /workdir/$USER/FormicidaeMolecularEvolution/TranslatedData/OutputFiles/translated* /workdir/$USER/OrthoFinder/fasta
  cd /workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/fasta
  rename translated '' translated*
  cd ../


  # Now run OrthoFinder:
  #for f in *.fasta ; do python /programs/OrthoFinder-2.3.8_source/orthofinder/tools/primary_transcript.py $f ; done
  orthofinder.py -S diamond -I 5 -t 32 -a 4 -f /workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/fasta -M msa -p /workdir/tmp

  echo Finished running OrthoFinder v. $1

# If no version number is given, produce an error
else
  echo 'Please provide the version of OrthoFinder you want to run, either 2.4.0 or 2.3.8'

fi
