#!/bin/bash

# The command to run this script is ./scripts/DataOrthofinder [version of OrthFinder, either 2.4.1 or 2.3.8] [Full path to correct species tree]
# This is structured as an if/elif/then statement to allow you to choose the version of OrthoFinder you want to run on Cornell's BioHPC.
if [[ $1 == '2.4.1' ]]; then
  echo __________________________________________________
  echo Running the most recent version of OrthoFinder.
  echo __________________________________________________
  # cd /workdir/$USER/FormicidaeMolecularEvolution

  # I think I actually want to use https://github.com/davidemms/OrthoFinder/releases/tag/2.4.1
   wget https://github.com/davidemms/OrthoFinder/archive/2.4.1.tar.gz
   tar -xzvf 2.4.1.tar.gz
   mv ./OrthoFinder-2.4.1 ./5_OrthoFinder
  #  git clone https://github.com/davidemms/OrthoFinder.git

  # set environment
  export PATH=/programs/python2_link:$PATH
  export PATH=/programs/FastTree-2.1.10:$PATH
  export PATH=/workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/orthofinder:/workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/orthofinder/bin:/programs/muscle:/programs/RAxML-8.2.12:/programs/raxml-ng_v0.8.1:/programs/iqtree-1.6.10-Linux/bin:/programs/mafft/bin:$PATH

  mkdir /workdir/tmp
  mkdir ./5_OrthoFinder/fasta
  cp ./4_1_TranslatedData/OutputFiles/translated* ./5_OrthoFinder/fasta
  cd ./5_OrthoFinder/fasta
  rename translated '' translated*
  cd ../

  # Run Orthofinder:
  ./orthofinder.py -S diamond -I 5 -t 32 -a 4 -f /workdir/$USER/FormicidaeMolecularEvolution/5_OrthoFinder/fasta -M msa -p /workdir/tmp -s $2
  # We then need to reanlyze, supplying the known species tree: To reanalyse with a different species tree use the options
  # ./orthofinder.py -S diamond -I 5 -t 32 -a 4 -M msa -p /workdir/tmp -ft /workdir/$USER/FormicidaeMolecularEvolution/OrthoFinder/fasta/OrthoFinder/Results_"$2"  -s $3

  echo Finished running OrthoFinder v. $1
  #mv /workdir/$USER/FormicidaeMolecularEvolution/5_OrthoFinder/ /workdir/$USER/FormicidaeMolecularEvolution/5_OrthoFinder/
  rm 2.4.1.tar.gz

elif [[ $1 == '2.3.8' ]]; then
echo Running OrthoFinder v. $1
cd /workdir/$USER/FormicidaeMolecularEvolution

  # This script will run Orthofinder 2.3.8 on all of the genomes, identifying orthogroups (genes descended from a common gene in the common ancestor).

  # Make a directory in which to run OrthoFinder:
  mkdir ./5_OrthoFinder
  cd ./5_OrthoFinder
  mkdir ./fasta

  # First set up the BioHPC to run OrthoFinder:
  export PATH=/programs/python2_link:$PATH
  cp -r /programs/OrthoFinder-2.3.8_source/orthofinder $HOME/
  export PATH=$HOME/orthofinder:$HOME/orthofinder/bin:/programs/muscle:/programs/RAxML-8.2.12:/programs/raxml-ng_v0.8.1:/programs/iqtree-1.6.10-Linux/bin:/programs/mafft/bin:$PATH
  export PATH=/programs/FastTree-2.1.10:$PATH
  mkdir /workdir/tmp

  # Copy the input files to the primary_transcripts directory:
  cp /workdir/$USER/FormicidaeMolecularEvolution/4_1_TranslatedData/OutputFiles/translated* /workdir/$USER/5_OrthoFinder/fasta
  cd /workdir/$USER/FormicidaeMolecularEvolution/5_OrthoFinder/fasta
  rename translated '' translated*
  cd ../


  # Now run OrthoFinder:
  #for f in *.fasta ; do python /programs/OrthoFinder-2.3.8_source/orthofinder/tools/primary_transcript.py $f ; done
  orthofinder.py -S diamond -I 5 -t 32 -a 4 -f /workdir/$USER/FormicidaeMolecularEvolution/5_OrthoFinder/fasta -M msa -p /workdir/tmp

  echo Finished running OrthoFinder v. $1

# If no version number is given, produce an error
else
  echo 'Please provide the version of OrthoFinder you want to run, either 2.4.1 or 2.3.8'

fi
