#!/bin/bash

# The command to run this is `./scripts/DataRunPAL2NAL ./scripts/inputurls.txt
while read -r line;
do
  # Start setting up variables from the inputurls file:
  # This will get the species abbreviation from the inputurls file:
  export abbrev=`echo "$line" | awk -F',' '{print $4}'`
  echo This is the species abbreviation: $abbrev

  #export output=$abbrev"_codon_alignment.fasta"

  export alnFile=./6_1_SpeciesMSA/proteins_"$abbrev".fasta
  export nucFile="./6_2_FilteredCDS/filtered_"$abbrev"_cds.fasta"
  export output=alignedCDS_$abbrev".fasta"

  echo Running PAL2NAL on $alnFile and $nucFile
  # ex:   ./scripts/pal2nal.v14/pal2nal.pl  ./5_1_SpeciesMSA/proteins_mpha.fasta  ./5_2_FilteredCDS/filtered_mpha_cds.fasta  -output fasta > test.fasta
  ./scripts/pal2nal.v14/pal2nal.pl  $alnFile  $nucFile  -output fasta > $output

  mkdir ./7_PAL2NALOutput
  mv $output ./7_PAL2NALOutput/$output

done < $1
