#!/bin/bash

# Export required paths:
export LD_LIBRARY_PATH=/usr/local/gcc-7.3.0/lib64:/usr/local/gcc-7.3.0/lib

# Make a directory for BUSTED[S] outputs:
mkdir ./7_2_RemovedStops

# Download the newest version of HyPhy:
export PATH=/home/$USER/miniconda3/bin:$PATH
conda install -c bioconda hyphy

# For all of the aligned, nucleotide orthogroup files in ./7_1_CDSOrthogroups, go through and mask terminal stop codons.
for f in 7_1_CDSOrthogroups/MultipleSequenceAlignments/Output/*
do
  #echo $f
  export orthogroup=`echo "$f" | awk -F'/' '{print ($4)}' | awk -F'.' '{print ($1)}'`
  echo $orthogroup
  # This looks like: OG0000711_cds
  export cleanedFile="cleaned_"$orthogroup".fasta"
  echo __________________________________________________
  (echo 1; echo "./"$f; echo 1; echo ./7_2_RemovedStops/$cleanedFile) | /programs/hyphy-2.5.15/bin/hyphy /programs/hyphy-2.5.15/share/hyphy/TemplateBatchFiles/CleanStopCodons.bf
  echo __________________________________________________

done
