#!/bin/bash

# I am going to have an input file that is a tab-delimited text file with data urls and desired file names to send the download.

# The command to run this is `./DataDownload [input file]`. This will read in each line of the input file; create a variable that is the url from which to download the data, based on the first field of the line of the input file; it will create a temporary file that holds the individual tree for that gene; and will then send those pieces of information to HyPhy to be run.
  while read -r line;
  do
    # This creates a variable, url, that holds the information about the download url on this line of the input file:
    export url=`echo "$line" | awk -F',' '{print $1}'`
    # This uses the second field on that line to get the file name where that data should ultimately be sent:
    export name=`echo "$line" | awk -F',' '{print $2}'`
    # This tells us what the zipped, downloaded file should be sent to:
    if [[ $url == *.zip ]]
      then
        export zipFn=$name.zip
      else [[ $url == *.gz ]]
        export zipFn=$name.gz
    fi

    mkdir ./RawData
    cd ./RawData

    # These lines print the file name variable information to the console so you can see it:
    echo __________________________________________________
    echo Dowloading data from the url: $url
    echo Downloading the zipped data to $zipFn
    echo wget $url -O $zipFn

    # This sends the download url to wget, unzips the downloaded file, and renames it to the name you indicated in the input file.
    wget $url -O $zipFn

    if [[ $zipFn == *.zip ]]
      then
        unzip -p $zipFn > $name
        echo Unzipping $zipFn to $name
      else [[ $zipFn == *.gz ]]
        gunzip -f $zipFn > $name
        echo Unzipping $zipFn to $name
    fi

    rm $zipFn
    echo __________________________________________________

    cd ../

  done < $1

  # The command to run this script is `./DataDownload [input file]`. This will read in each line of the big tree file; create a variable that is the name of the alignment file, based on the first field of the line of the big tree file; it will create a temporary file that holds the individual tree for that gene; and will then send those pieces of information to HyPhy to be run.
