#!/bin/bash

# Export required paths:
export LD_LIBRARY_PATH=/usr/local/gcc-7.3.0/lib64:/usr/local/gcc-7.3.0/lib

# Make a directory for BUSTED[S] outputs:
mkdir ./bustedResults

# Download the newest version of HyPhy:
export PATH=/home/$USER/miniconda3/bin:$PATH
conda install -c bioconda hyphy

for f in CDSOrthogroups/MultipleSequenceAlignments/Output/*
do
  #echo $f
  export orthogroup=`echo "$f" | awk -F'/' '{print ($4)}' | awk -F'.' '{print ($1)}'`
  export cleanedFile="cleaned_"$orthogroup".fasta"
  echo __________________________________________________
  (echo 1; echo "./"$f; echo 1; echo ./bustedResults/$cleanedFile) | /programs/hyphy-2.5.15/bin/hyphy /programs/hyphy-2.5.15/share/hyphy/TemplateBatchFiles/CleanStopCodons.bf
  echo __________________________________________________

  #export bustedFile="./bustedResults/busted_"$orthogroup".fasta"

  #hyphy busted --alignment $bustedFile --tree ./Tree/StudyTree.tre --srv Yes

done
