#!/bin/bash

# I am going to have an input file that is a tab-delimited text file with data urls and desired file names to send the download.

# The command to run this script is `./scripts/FunctionalAnnotationInterProScanAndKinFin inputurls_full.txt /workdir/mb2337/FormicidaeMolecularEvolution/5_OrthoFinder/fasta/`.
  while read -r line;
  do
    # This uses the second field on that line to get the species abbreviation:
    export name=`echo "$line" | awk -F',' '{print $4}'`
    # Construct the name of the protein file:
    export proteinName="$name"_filteredTranscripts.fasta

    # Make a directory for these analyses:
    mkdir ./11_InterProScan
    cd ./11_InterProScan

    # This will check if interproscan is installed and located
    if [ -d "./interproscan-5.52-86.0" ]
    then
        echo "InterProScan installed."
        # This will check if a species has already been annotated and move to the next species if so.
        FILE=./interproscan-5.52-86.0/out/$proteinName.tsv
        if [ -f "$FILE" ]; then
            echo "$FILE exists; moving to next species."
        # If the species has not yet been annotated, this will copy the proteins file from the OrthoFinder directory and then run InterProScan on it.
        else
          cp $2$proteinName ./interproscan-5.52-86.0/
          sed -i'.original' -e "s|\*||g" ./interproscan-5.52-86.0/$proteinName
          rm ./interproscan-5.52-86.0/*.original
          echo __________________________________________________
          cd ./interproscan-5.52-86.0
          mkdir ./out
          ./interproscan.sh -i $proteinName -d out/ -t p --goterms -appl Pfam -f TSV
          cd ../
        fi

      # Now concatenate all of the annotated protein files into a single file which can be passed to KinFin for orthogroup-level functional annotation.
      cat ./interproscan-5.52-86.0/out/*.tsv > all_proteins.tsv

      # Install kinfin:
      git clone https://github.com/DRL/kinfin.git
      cd kinfin
      ./install
      ./kinfin

      # This will convert the concatenated InterProScan files into a format readable by KinFin.
      ./kinfin/scripts/iprs2table.py -i all_proteins.tsv --domain_sources Pfam

      # Copy Orthofinder files that are needed to the KinFin directory:
      cp ../5_OrthoFinder/fasta/OrthoFinder/Results*/Orthogroups/Orthogroups.txt ./
      cp ../5_OrthoFinder/fasta/OrthoFinder/Results*/WorkingDirectory/SequenceIDs.txt ./
      cp ../5_OrthoFinder/fasta/OrthoFinder/Results*/WorkingDirectory/SpeciesIDs.txt ./

      # Create the KinFin configuration file:
      echo '#IDX,TAXON' > config.txt
      sed 's/: /,/g' SpeciesIDs.txt | \
          cut -f 1 -d"." \
          >> config.txt

      # Run the KinFin functional annotation script:
      # This failed for me until I commented out 'ax.set_facecolor('white')' on lines 681 and 1754 of ./kinfin/src/kinfin.py. Once I commented them out with vim it worked fine.
      ./kinfin/kinfin --cluster_file Orthogroups.txt --config_file config.txt --sequence_ids_file SequenceIDs.txt --functional_annotation functional_annotation.txt

    else
        echo "InterProScan not installed; installing now."
        wget http://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.52-86.0/interproscan-5.52-86.0-64-bit.tar.gz
        tar -xzvf interproscan-5.52-86.0-64-bit.tar.gz

        cp $2$proteinName ./interproscan-5.52-86.0/
        sed -i'.original' -e "s|\*||g" ./interproscan-5.52-86.0/$proteinName
        rm ./interproscan-5.52-86.0/*.original
        echo __________________________________________________
        cd ./interproscan-5.52-86.0
        mkdir ./out
        ./interproscan.sh -i $proteinName -d out/ -t p --goterms -appl Pfam -f TSV
        cd ../
    fi
    cd ../
  done < $1
