#!/bin/bash

# Select a set of 100 random orthogroups that will be used for all 50 iterations:
ls 9_3_BustedPHResults/workerReproductionQueens/*.json > allOrthogroups.txt
shuf -n 100 allOrthogroups.txt > subsetOrthogroupFiles.txt
cut -d'_' -f4 subsetOrthogroupFiles.txt > subsetOrthogroups.txt
echo Finished getting random orthogroups at `date` >> bootstrappingLog.txt

# Copy trees for randomly selected orthogroups to a directory:
rm -R ./bootstrappingTreeFiles
mkdir ./bootstrappingTreeFiles
while read -r line;
do
  export rawTreeFile=/workdir/mb2337/FormicidaeMolecularEvolution/allGeneTrees/$line"_tree.txt"
  cp $rawTreeFile ./bootstrappingTreeFiles
done < subsetOrthogroups.txt

# Run this fifty times (randomly labelling foreground, running BUSTED-PH):
i=0
while [ $i -ne 50 ]
do
  i=$(($i+1))
  echo "$i"

  # Note the start time:
  echo Starting $i round of bootstrapping at `date` >> bootstrappingLog.txt

  # Get a random list of X foreground species:
  shuf -n $2 ./scripts/inputurls_full.txt > subsetSpeciesFull.txt
  cut -d',' -f4 subsetSpeciesFull.txt > subsetSpecies.txt
  rm subsetSpeciesFull.txt
  echo Finished getting random species at `date` >> bootstrappingLog.txt

  # Label trees with your random species:
  echo "Labelling trees with foreground species"
  export LD_LIBRARY_PATH=
  rm -R ./9_1_LabelledPhylogenies/bootstrapping/
  Rscript ./scripts/LabellingPhylogeniesHYPHY.R /workdir/mb2337/FormicidaeMolecularEvolution/bootstrappingTreeFiles subsetSpecies.txt bootstrapping

  echo Finished labelling trees with random species at `date` >> bootstrappingLog.txt

  # Run BUSTED-PH on those orthogroups/trees
  # Export required paths:
  export LD_LIBRARY_PATH=/usr/local/gcc-7.3.0/lib64:/usr/local/gcc-7.3.0/lib

  # Make a directory for BUSTED[S] outputs:
  mkdir ./9_3_BustedPHResults
  mkdir ./9_3_BustedPHResults/bootstrapping

  # Add HyPhy to your path:
  module load gcc/7.3.0
  export PATH=/programs/hyphy-20210923/bin:$PATH
  cd ./9_3_BustedPHResults
  git clone https://github.com/veg/hyphy-analyses.git
  cd ../

  # List our sequence files for the boostrap run:
  #echo "List our sequence files for the boostrap run:"
  rm sequencefileList.txt
  while read -r line;
  do
    export removedStopFile=/workdir/mb2337/FormicidaeMolecularEvolution/8_2_RemovedStops/cleaned_$line"_cds.fasta"
    echo $removedStopFile >> sequencefileList.txt
  done < subsetOrthogroups.txt

  # Split the list of allowable input files into a specified number of chunks:
  echo "Split the list of allowable input files into a specified number of chunks:"
  export chunkNumber="l/"$1
  split --number=$chunkNumber --additional-suffix=.txt -d sequencefileList.txt bootstrapping_bustedphFileList

  # Create a file listing those chunks:
  echo "Create a file listing those chunks:"
  ls bootstrapping_bustedphFileList* > bootstrapping_chunkList.txt

  # Create a holder for the chunks:
  export batchSize=$1
  export currentBatch=0
  export batchFileNames=()

  # while reading each line in our list of chunked files,
  #echo "Running BUSTED-PH"
  while read -r line;
  do
    export batchFile=$line
    batchFileNames+=($batchFile)

    if [ ${#batchFileNames[@]} -eq $batchSize ]; then
      for batchFile in ${batchFileNames[@]} ; do
        echo $batchFile
        sleep 10 &
        ./scripts/SingleBustedPHRun $batchFile  9_1_LabelledPhylogenies/bootstrapping/ bootstrapping &
        # ./scripts/SingleBustedPHRun bootstrapping_bustedphFileList00.txt 9_1_LabelledPhylogenies/bootstrapping bootstrapping

        # cat /workdir/mb2337/FormicidaeMolecularEvolution/8_2_RemovedStops/cleaned_OG0015422_cds.fasta 9_1_LabelledPhylogenies/bootstrapping/bootstrappingLabelled_OG0015422_tree.txt >> ./9_3_BustedPHResults/bootstrapping/bootstrapping_OG0015422_BUSTEDPH.fas
        # HYPHYMP /workdir/mb2337/FormicidaeMolecularEvolution/9_3_BustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment ./9_3_BustedPHResults/bootstrapping/bootstrapping_OG0001903_BUSTEDPH.fas --srv Yes
      done
      wait
      batchFileNames=()
    fi
  done < bootstrapping_chunkList.txt

  mv 9_3_BustedPHResults/bootstrapping/ "9_3_BustedPHResults/"$i"bootstrapping/"
  mv subsetSpecies.txt $i"subsetSpecies.txt"
done
