#!/bin/bash

export cdsFile=$1
export pathToTrees=$2
export prefix=$3

#sleep 5
#echo Finish $cdsFile
#exit

#echo the coding sequence alignment file is $cdsFile
# The tree file needs to look like OG0002680_tree.txt. $f looks like  /8_2_RemovedStops/cleaned_OG0002680_cds.fasta.
export orthogroupNumber=`echo "$cdsFile" | awk -F'_' '{print ($4)}'`
#echo The orthogroup number is $orthogroupNumber
# 9_1_LabelledPhylogenies/workerPolymorphism/workerPolymorphismLabelled_OG0007231_tree.txt
export treeFile=$3"Labelled_"$orthogroupNumber"_tree.txt"
export catFile="./9_3_BustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"

if [ -f "$catFile" ]; then
    echo "$catFile exists; BUSTED-PH already performed on this orthogroup."

else
  if [ -f "$pathToTrees$treeFile" ]; then
      echo "$pathToTrees$treeFile exists."
      if [ -f "$cdsFile" ]; then
          echo "$cdsFile exists."
          cat $cdsFile $pathToTrees$treeFile >> "./9_3_BustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
          export inputFile="./9_3_BustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
          # HYPHYMPI /workdir/mb2337/FormicidaeMolecularEvolution/9_3_BustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment ./9_3_BustedPHResults/workerPolymorphism/workerPolymorphism_OG0013357_BUSTEDPH.fas --srv Yes
          HYPHYMP /workdir/mb2337/FormicidaeMolecularEvolution/9_3_BustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment $inputFile --srv Yes
      else
          echo "."
      fi
  else
      echo "."
  fi
fi
