#!/bin/bash

export cdsFile=$1
export pathToTrees=$2
export prefix=$3

#sleep 5
#echo Finish $cdsFile
#exit

#echo the coding sequence alignment file is $cdsFile
# The tree file needs to look like OG0002680_tree.txt. $f looks like  /8_2_RemovedStops/cleaned_OG0002680_cds.fasta.
export orthogroupNumber=`echo "$cdsFile" | awk -F'_' '{print ($4)}'`
#echo The orthogroup number is $orthogroupNumber
# 9_1_LabelledPhylogenies/workerPolymorphism/workerPolymorphismLabelled_OG0007231_tree.txt
export treeFile=$3"Labelled_"$orthogroupNumber"_tree.txt"
export catFile="./9_3_BustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"

if [ -f "$catFile" ]; then
    echo "$catFile exists; BUSTED-PH already performed on this orthogroup."

else
  if [ -f "$pathToTrees$treeFile" ]; then
      echo "$pathToTrees$treeFile exists."
      if [ -f "$cdsFile" ]; then
          echo "$cdsFile exists."
          cat $cdsFile $pathToTrees$treeFile >> "./9_3_BustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
          export inputFile="./9_3_BustedPHResults/"$prefix"/"$prefix"_"$orthogroupNumber"_BUSTEDPH.fas"
          # HYPHYMPI /workdir/mb2337/FormicidaeMolecularEvolution/9_3_BustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment ./9_3_BustedPHResults/workerPolymorphism/workerPolymorphism_OG0013357_BUSTEDPH.fas --srv Yes
          HYPHYMP /workdir/mb2337/FormicidaeMolecularEvolution/9_3_BustedPHResults/hyphy-analyses/BUSTED-PH/BUSTED-PH.bf --alignment $inputFile --srv Yes
      else
          echo "."
      fi
  else
      echo "."
  fi
fi



#export fullTreeFile=$pathToTrees$treeFile
#export output="./8_3_BustedResults/"$orthogroupNumber"_busted.json"
#if [ -f "$output" ]; then
  #echo "$output exists; this gene has been previously analysed."
#else
  #if [ -f "$fullTreeFile" ]; then
    #echo "$treeFile exists; running BUSTED[S]."
    #echo Removing any special characters in $fullTreeFile
    #sed -i'.original' -e "s|\||_|g" $fullTreeFile
    #rm $fullTreeFile.original

    # Example cds file: ./8_2_BustedResults/cleaned_OG0013039_cds.fasta
    # Example gene tree file: /workdir/mb2337/FormicidaeMolecularEvolution/4_OrthoFinder/fasta/OrthoFinder/Results_Nov19_1/Resolved_Gene_Trees/OG0013039_cds.fasta
    #hyphy busted --alignment /workdir/mb2337/FormicidaeMolecularEvolution/8_2_RemovedStops/cleaned_OG00012768_cds.fasta --tree /workdir/mb2337/FormicidaeMolecularEvolution/4_OrthoFinder/fasta/OrthoFinder/Results_Nov24/Resolved_Gene_Trees/OG00012768_tree.txt --srv Yes CPU=16
    #echo Running BUSTED[S] on $cdsFile and $fullTreeFile
    #HYPHYMPI busted --alignment $cdsFile --tree $fullTreeFile --srv Yes --output "./8_3_BustedResults/"$orthogroupNumber"_busted.json"
    #hyphy busted --alignment 8_2_RemovedStops/cleaned_OG0008294_cds.fasta --tree 5_OrthoFinder/fasta/OrthoFinder/Results_Jul13/Gene_Trees/OG0008294_tree.txt --srv Yes --output ./8_3_BustedResults/OG0008294_busted.json
  #else
    #echo "$treeFile does not exist because this orthogroup consists of three or fewer sequences. Skipping BUSTED[S]."
  #fi
#fi
